project:
  type: website
  output-dir: docs

website:
  title: "Elumity Documentation"
  search:
    location: sidebar
  sidebar:
    style: "docked"
    contents:
      - section: "Get Started"
        contents:
          - tutorial-hello-elumity.qmd
          - tutorial-library.qmd
          - tutorial-cards.qmd
          - tutorial-quiz.qmd
      - section: "Library"
        contents:
          - library-nav.qmd
          - library-tree.qmd
          - library-view.qmd
      - section: "Cards"
        contents:
          - cards-create.qmd
          - cards-public.qmd
          - cards-share.qmd
      - section: "Quiz"
        contents:
          - quiz-create.qmd
          - quiz-add-custom.qmd
      - section: "Settings"
        contents:
          - settings-profile.qmd
          - settings-delete.qmd
      - section: "FAQs"
        contents:
          - faqs.qmd

format:
  html:
    toc: true
    theme: cosmo
    css: styles.css
    grid:
      sidebar-width: 350px
      margin-width: 350px
      gutter-width: 2em


